all:
	g++ -O3 -D insertionSort -o insertionSort ./src/sort.cpp ./src/parser.cpp
	g++ -O3 -D mergeSort -o mergeSort ./src/sort.cpp ./src/parser.cpp
	g++ -O3 -D quickSort -o quickSort ./src/sort.cpp ./src/parser.cpp
	g++ -O3 -D heapSort -o heapSort ./src/sort.cpp ./src/parser.cpp
clean:
	$(RM) insertionSort mergeSort quickSort heapSort

